
project_id = "eswfrzdqxsaizkdswxfn"
[api]
enabled = true
[functions]
[functions.telegram-connector]
verify_jwt = false
import_map = "import_map.json"
[functions.telegram-realtime]
verify_jwt = false
[functions.validate-registration]
verify_jwt = false
